### ISSUE TITLE
AttributeError: 'FormattedValue' object has no attribute 's'

### ISSUE THREAD

**Issue by cioma** [JarryShaw/f2format#1]
I have a Python source file (see attachment) that gives the following error when I try to convert it with f2format v0.4.3 on Ubuntu 18.04 64-bit using Python 3.6.5:
`AttributeError: 'FormattedValue' object has no attribute 's'`
[register.py.zip](https://github.com/JarryShaw/f2format/files/2958071/register.py.zip)

**Comment by JarryShaw** [comment]
Seems it's a grammar I didn't think of. Thx for reporting.

**Comment by cioma** [comment]
Many thanks!
There is another file that fails with different error, I'll open a separate issue for that.

**Comment by JarryShaw** [comment]
> Expressions cannot contain ':' or '!' outside of strings or parentheses, brackets, or braces. The exception is that the '!=' operator is allowed as a special case. (c.f. [PEP 498](https://www.python.org/dev/peps/pep-0498/), thx to @gousaiyang)

As described in [PEP 498](https://www.python.org/dev/peps/pep-0498/#format-specifiers), *f-string* may contains **evaluated expressions** as format specifiers. `AttributeError` and `SyntaxError` in this issue and issue #2 are both because of this.

* for `ast.FormattedValue.format_spec`, which is an `ast.JoinedStr`, the elements in its `values` (a `list`)  attribute can either be of an `ast.Str` (thus has an `s` attribute) or other types (`ast.Name`) in this case [`AttributeError` resolved in v0.4.4.dev1 but other types not reviewed]
* when `f2format` extracts all entries of expressions in the *f-string*s, it uses brute force to find the end of expression; when the format specifiers are expressions, it has problem to find the right ending point [to revise `f2format.core.convert.find_rbrace`, maybe try some cleverer ways]

**Comment by cioma** [comment]
I'll also see a way to modify f-string in my code to make it easier for f2format.

**Comment by cioma** [comment]
For register.py the problem was on line 182: it has unnecessary extra curly braces around value_hex_width:
`value_hex = f'0x{(bitstring.Bits(4 - len(bit_value) % 4) + bit_value).hex.upper() if len(bit_value) % 4 != 0 else bit_value.hex.upper():{value_hex_width}}'`

After changing it to the following it got converted fine:
`value_hex = f'0x{(bitstring.Bits(4 - len(bit_value) % 4) + bit_value).hex.upper() if len(bit_value) % 4 != 0 else bit_value.hex.upper():value_hex_width}'`

**Comment by cioma** [comment]
It seems in my case f2format fails when trying to convert an f-string that has format specifiers which contain evaluated expressions (see [PEP 498, Format specifiers](https://www.python.org/dev/peps/pep-0498/#format-specifiers))

E.g. a line like this:
`bits = f'{bitfield.bits:{bits_width}}'`

Shall be converted like this:
`bits = '{:{}}'.format(bitfield.bits, bits_width)`

**Comment by JarryShaw** [comment]
This issue should have been revolved in version __0.5.0__. Thx for your report @cioma

**Comment by cioma** [comment]
Seems to be working fine for me, many thanks!
